# Generated by Django 5.0.5 on 2024-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
