# Generated by Django 5.0.5 on 2024-05-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_userprofile_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_user.userrole'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
