# Generated by Django 5.0.5 on 2024-05-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_userprofile_is_blocked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.PROTECT, related_name='updated_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
