# Generated by Django 5.0.5 on 2024-05-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_blocked',
            new_name='is_active',
        ),
    ]
