# Generated by Django 5.0.5 on 2024-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_userprofile_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
